### ISSUE TITLE
Hexdecimal Option or Problem

### ISSUE THREAD

**Issue by devbluen** [itsneufox/PAWN-Painter-VSC#1]
I noticed that the extension colors the variable, however in some occasions and themes it looks strange, you could add an option to make this work and leave it disabled by default.

By the way, is this a problem or an intensional function.

![image](https://github.com/user-attachments/assets/dc05f344-4d0b-4461-8968-0f650db19211)

**Comment by devbluen** [comment]
Completely ignore what I said above, I'm sorry.
I found the functionality in the settings for this function.

**Comment by itsneufox** [comment]
The main functionality of the extension is to colour text strings inline in the code, allowing programmers to see the colours accurately.

I'm glad you found the settings and adjusted them to suit your workflow.

**Do you think it would be best to have a splash screen explaining the features and settings on the first startup of the extension?**

Thanks for your time!

**Comment by devbluen** [comment]
Your extension is perfect, incredible; it was exactly what I and half of the SAMP community were looking for and needed to help with our development.

I want to take advantage of this issue to report a problem I encountered while using some functions. I will attach a screenshot below.

![image](https://github.com/user-attachments/assets/2874a8e9-233f-4c68-ab97-2664c230f9fd)
In some functions that use an int in sequence, it recognizes it as a coloring

**Comment by itsneufox** [comment]
Will be fixed in the next update

**Comment by itsneufox** [comment]
Fixed in 1.3.0
